version: 2.1
orbs:
  # we will use stable circleci orbs for node, aws-cli and aws-eb
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@2.0.3
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  
  # we will only start the pipeline if the developer deployed to the main branch of the github repo
triggers:
  - filters:
      branches:
        only:
          - main
jobs:
  build:
    docker:
      # We will use this docker image as it is the latest stable version
      - image: "cimg/base:stable"
    steps:
      - node/install:
          install-yarn: true
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      # we will install the dependencies for the back end and front end apps
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      - run:
          name: Back-End Deploy
          command: |
            npm run api:deploy  
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Front-End openssl
          command: |
            npm run frontend:openssl         
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy